name: AITools
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - intel
dependencies:
  - black
  - debugpy
  - ipython
  - jedi-language-server
  - pyright
  - jupyter
  - matplotlib
  - memory_profiler
  - line_profiler
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - textblob
  - nltk
  - scipy
  - pyspellchecker
  - keras
  - kaggle
  - numba
  - bottleneck
  - mkl
  - scikit-learn-intelex
  - intel-cmplr-lib-rt
  - numba-dpex
  - xgboost
  - seaborn
  - tensorflow-gpu
  - cmake
  - ca-certificates
  - certifi
  - openssl
  - tabulate
  - nvidia-ml-py
  - pillow
  - py-opencv
  - nvtx
  - pexpect
  - psutil
  - future
  - jupyterlab
  - notebook
  - mock
  - portpicker
  - h5py
  - keras-preprocessing
  - keras-applications
  - tensorboard
  - jupytext
  - tensorflow-datasets
  - bazel
  - mkl-dnn
  - nccl
  - nsight-compute
  - cudnn
  - lxml
  - pytables
  - pip
  - cxx-compiler
  - mpi4py
  - ccache
  - numexpr
  - pip:
     - tensorrt
     - horovod[tensorflow,keras]
variables:
  HOROVOD_GPU_OPERATIONS: NCCL
