name: AITools
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - intel
dependencies:
  - python=3.9
  - black
  - debugpy
  - ipython
  - jedi-language-server
  - pyright
  - jupyter
  - matplotlib
  - memory_profiler
  - line_profiler
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - textblob
  - nltk
  - scipy
  - pyspellchecker
  - keras
  - kaggle
  - numba
  - bottleneck
  - mkl
  - scikit-learn-intelex
  - intel-cmplr-lib-rt
  - numba-dpex
  - xgboost
  - seaborn
  - tensorflow-gpu
  - tabulate
  - keras-preprocessing
  - keras-applications
  - tensorboard
  - jupytext
  - tensorflow-datasets
  - mkl-dnn
  - cudnn
  - lxml
  - pytables
  - scikit-ipp
  - singularityce
  - horovod
  - pip
  - rdma-core
  - nccl
  - nsight-compute
  - ucx
  - cutensor
  - openmpi
  - dpcpp-cpp-rt
  - dpnp
  - impi-devel
  - mkl-dpcpp
  - modin-all
  - pip:
     - tensorrt
